# Generated by Django 6.0.3 on 2026-04-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='daily_calorie_limit',
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='workout',
            name='calories_burned',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
