# Generated by Django 6.0.3 on 2026-05-15 00:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_workout_calories_burned_workout_created_by'),
        ('core', '0004_fix_core_user_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouttracker',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.workout'),
        ),
        migrations.AlterField(
            model_name='goaltest',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='kcaltracker',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='progresstracker',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='watertracker',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='workouttracker',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.DeleteModel(
            name='Workout',
        ),
    ]
