# Generated by Django 6.0.3 on 2026-04-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_seed_workouts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_recipe', models.CharField(db_index=True, max_length=255)),
                ('calories', models.PositiveIntegerField(db_index=True)),
                ('protein', models.FloatField(db_index=True)),
                ('fat', models.FloatField(db_index=True)),
                ('carbs', models.FloatField(db_index=True)),
                ('goal_type', models.CharField(choices=[('weight_loss', 'Weight Loss'), ('muscle_gain', 'Muscle Gain'), ('maintenance', 'Maintenance')], db_index=True, default='maintenance', max_length=20)),
            ],
            options={
                'ordering': ('name_recipe',),
            },
        ),
    ]
