# Generated by Django 6.0.3 on 2026-05-15 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='calories_burned',
            field=models.PositiveIntegerField(default=0, help_text='Estimated calories burned per workout session.'),
        ),
        migrations.AddField(
            model_name='workout',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_workouts', to=settings.AUTH_USER_MODEL),
        ),
    ]
