# Generated by Django 6.0.3 on 2026-05-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_workout_calories_burned_workout_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workout",
            name="calories_burned",
            field=models.PositiveIntegerField(
                default=200,
                help_text="Estimated calories burned per workout session.",
            ),
        ),
    ]
