from django.urls import path

from .views import (
    admin_analytics_api,
    admin_analytics_page,
    admin_food_delete_api,
    admin_foods_api,
    admin_foods_page,
    admin_panel_page,
    admin_user_block_api,
    admin_users_api,
    admin_users_page,
    admin_workout_delete_api,
    admin_workouts_api,
    calories_stats_api,
    dashboard_stats_api,
    exercise_page,
    login_page,
    macros_today_api,
    mark_workout_done,
    notification_mark_read_api,
    notifications_api,
    notifications_page,
    nutrition_today_api,
    profile_page,
    recipes_page,
    signup_page,
    stats_dashboard,
    test_page,
    water_week_stats_api,
    workout_list,
    workouts_week_stats_api,
)

urlpatterns = [
    path("", login_page, name="home_page"),
    path("login/", login_page, name="login_page"),
    path("signup/", signup_page, name="signup_page"),
    path("profile/", profile_page, name="profile_page"),
    path("notifications/", notifications_page, name="notifications_page"),
    path("pages/test/", test_page, name="test_page"),
    path("pages/exercise/", exercise_page, name="exercise_page"),
    path("pages/recipes/", recipes_page, name="recipes_page"),
    path("admin-panel/", admin_panel_page, name="admin_panel_page"),
    path("admin-panel/users/", admin_users_page, name="admin_users_page"),
    path("admin-panel/foods/", admin_foods_page, name="admin_foods_page"),
    path("admin-panel/analytics/", admin_analytics_page, name="admin_analytics_page"),
    path("workouts/", workout_list, name="workout_list"),
    path("workouts/<int:workout_id>/done/", mark_workout_done, name="mark_workout_done"),
    path("dashboard/", stats_dashboard, name="stats_dashboard"),
    path("api/stats/dashboard/", dashboard_stats_api, name="dashboard_stats_api"),
    path("api/stats/calories/", calories_stats_api, name="calories_stats_api"),
    path("api/stats/calories", calories_stats_api),
    path("api/stats/macros/today/", macros_today_api, name="macros_today_api"),
    path("api/stats/macros/today", macros_today_api),
    path("api/stats/workouts/week/", workouts_week_stats_api, name="workouts_week_stats_api"),
    path("api/stats/workouts/week", workouts_week_stats_api),
    path("api/stats/water/week/", water_week_stats_api, name="water_week_stats_api"),
    path("api/stats/water/week", water_week_stats_api),
    path("api/nutrition/today", nutrition_today_api, name="nutrition_today_api"),
    path("api/notifications", notifications_api, name="notifications_api"),
    path(
        "api/notifications/<int:notification_id>/read",
        notification_mark_read_api,
        name="notification_mark_read_api",
    ),
    path("api/admin/users/", admin_users_api, name="admin_users_api"),
    path("api/admin/users/<int:user_id>/block/", admin_user_block_api, name="admin_user_block_api"),
    path("api/admin/foods/", admin_foods_api, name="admin_foods_api"),
    path("api/admin/foods/<int:item_id>/", admin_food_delete_api, name="admin_food_delete_api"),
    path("api/admin/workouts/", admin_workouts_api, name="admin_workouts_api"),
    path(
        "api/admin/workouts/<int:item_id>/",
        admin_workout_delete_api,
        name="admin_workout_delete_api",
    ),
    path("api/admin/analytics", admin_analytics_api, name="admin_analytics_api"),
]
