# Generated by Django 6.0.3 on 2026-04-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=120, null=True)),
                ('instructions', models.TextField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('calories', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
